[tool.black]
line-length = 120
target-version = ['py311']
force-exclude = '''test'''

[tool.coverage.run]
omit = ["tests/*", "main.py", "release_notes_presence_check/github_repository.py"]

[tool.mypy]
check_untyped_defs = true
exclude = "tests"
